using UnityEngine;

namespace Vanquish.Combat
{
    /// <summary>
    /// Phase 3B: hand-authored procedural meshes for the two silhouettes Unity's
    /// built-in primitives (`GameObject.CreatePrimitive`) genuinely cannot express —
    /// a proper tapering nose cone (missile seeker noses) and a tapered/swept wing
    /// planform (delta/variable-sweep wings). Everything else in
    /// `DroneVisualBuilder`/`MissileVisualBuilder` still uses
    /// `GameObject.CreatePrimitive` (cubes/cylinders/spheres/capsules), preserving the
    /// project's existing "no imported art assets" convention from Phase 1/2 — this
    /// class extends that convention rather than replacing it, for the specific two
    /// shapes where a box or a uniform-radius cylinder would look visibly wrong (a
    /// "delta wing" built from a rectangular cube isn't a delta wing).
    /// </summary>
    public static class PrimitiveMeshFactory
    {
        /// <summary>
        /// A circular-base cone tapering to a point, apex along local +Y (matching
        /// this project's existing convention of building shapes along Y and then
        /// rotating the whole parent by Euler(90,0,0) to point them along local Z —
        /// see DroneVisualBuilder's capsule/cube construction). Base sits at y=0,
        /// apex at y=height. Used for missile seeker noses (a real tapering nose,
        /// not a sphere or a flat-capped cylinder).
        /// </summary>
        public static Mesh CreateCone(float radius, float height, int radialSegments = 10)
        {
            radialSegments = Mathf.Max(3, radialSegments);
            var mesh = new Mesh { name = "ProceduralCone" };

            // Vertices: apex, then one ring of base vertices, then a duplicate base
            // center for the base cap. Base ring is duplicated (not shared with the
            // apex fan) only implicitly — this is a simple unsmoothed cone, flat
            // shading via per-triangle normals is acceptable for a small nose piece.
            var vertices = new Vector3[radialSegments + 2];
            vertices[0] = new Vector3(0f, height, 0f); // apex
            for (int i = 0; i < radialSegments; i++)
            {
                float angle = i / (float)radialSegments * Mathf.PI * 2f;
                vertices[i + 1] = new Vector3(Mathf.Cos(angle) * radius, 0f, Mathf.Sin(angle) * radius);
            }
            vertices[radialSegments + 1] = new Vector3(0f, 0f, 0f); // base center

            var triangles = new int[radialSegments * 3 * 2];
            int t = 0;
            for (int i = 0; i < radialSegments; i++)
            {
                int current = i + 1;
                int next = i + 2 > radialSegments ? 1 : i + 2;

                // Side face (apex -> ring).
                triangles[t++] = 0;
                triangles[t++] = current;
                triangles[t++] = next;

                // Base cap face (wound the opposite way so it faces downward).
                triangles[t++] = radialSegments + 1;
                triangles[t++] = next;
                triangles[t++] = current;
            }

            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        /// <summary>
        /// A symmetric (left+right) tapered wing planform extruded to a flat prism —
        /// covers both delta wings (tipChordLength ~0, large sweepBack) and
        /// variable-sweep wings (moderate taper, large sweepBack, per the caller's
        /// parameters) with one mesh generator, since both are "root chord at the
        /// centerline, tapering/sweeping out to each tip" shapes that a rectangular
        /// cube (the existing straight-FixedWing look) cannot represent. Built
        /// directly in the same local axes DroneVisualBuilder's existing wing cubes
        /// use (X = span, Z = chord/depth, Y = thickness) — no extra rotation needed
        /// by the caller, unlike CreateCone.
        /// </summary>
        public static Mesh CreateTaperedWing(float span, float rootChordLength, float tipChordLength,
            float sweepBack, float thickness)
        {
            float halfSpan = span * 0.5f;
            float halfThickness = thickness * 0.5f;
            float halfRootChord = rootChordLength * 0.5f;
            float halfTipChord = tipChordLength * 0.5f;

            // Planform corners (top-down, in the local X/Z plane), right half only —
            // the left half is generated by mirroring X. Leading edge sweeps back by
            // `sweepBack` from root to tip; trailing edge stays roughly straight
            // (typical of both real delta and variable-sweep planforms).
            Vector2 rootLeadingEdge = new Vector2(0f, halfRootChord);
            Vector2 rootTrailingEdge = new Vector2(0f, -halfRootChord);
            Vector2 tipLeadingEdge = new Vector2(halfSpan, halfRootChord - sweepBack);
            Vector2 tipTrailingEdge = new Vector2(halfSpan, tipLeadingEdge.y - tipChordLength);

            Vector2[] rightHalfPlanform = { rootLeadingEdge, tipLeadingEdge, tipTrailingEdge, rootTrailingEdge };

            var mesh = new Mesh { name = "ProceduralTaperedWing" };
            var vertices = new System.Collections.Generic.List<Vector3>();
            var triangles = new System.Collections.Generic.List<int>();

            AddWingHalf(rightHalfPlanform, halfThickness, mirrorX: false, vertices, triangles);
            AddWingHalf(rightHalfPlanform, halfThickness, mirrorX: true, vertices, triangles);

            mesh.SetVertices(vertices);
            mesh.SetTriangles(triangles, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        /// <summary>
        /// Extrudes an arbitrary convex planform polygon (wound consistently, e.g.
        /// leading edge root -> ... -> tip -> trailing edge tip -> ... -> root) into a
        /// flat prism, fan-triangulated from vertex 0 — works for a plain quad
        /// (CreateTaperedWing's 4-point delta/swept planform) or a hexagon
        /// (CreateKiteWing's 6-point cranked/double-delta planform) with no special
        /// casing, since a fan from vertex 0 triangulates any convex N-gon in N-2
        /// triangles.
        /// </summary>
        /// <summary>
        /// A cranked/double-delta "kite" planform — a broad, low-aspect-ratio flying
        /// wing whose leading edge sweeps at one angle from root to a "crank" point
        /// partway along the span, then at a different (steeper) angle from the crank
        /// to the tip, matching the real X-47B's cranked-kite silhouette (a plain
        /// single-sweep delta, which CreateTaperedWing already covers, reads as a
        /// simple triangle — the X-47B's distinctive "broad-shouldered" look
        /// specifically comes from that leading-edge crank). The trailing edge is
        /// similarly cranked (root -> crank -> tip) so the whole planform is a proper
        /// hexagon, not just a cranked leading edge glued to a straight trailing edge.
        /// Same local axes as CreateTaperedWing (X = span, Z = chord/depth, Y =
        /// thickness) — no extra rotation needed by the caller.
        /// </summary>
        public static Mesh CreateKiteWing(float span, float rootChordLength, float crankSpanFraction,
            float inboardSweepBack, float crankChordLength, float outboardSweepBack, float tipChordLength,
            float thickness)
        {
            float halfSpan = span * 0.5f;
            float halfThickness = thickness * 0.5f;
            float halfRootChord = rootChordLength * 0.5f;
            float crankX = halfSpan * Mathf.Clamp01(crankSpanFraction);

            float rootLeadingZ = halfRootChord;
            float rootTrailingZ = -halfRootChord;
            float crankLeadingZ = rootLeadingZ - inboardSweepBack;
            float crankTrailingZ = crankLeadingZ - crankChordLength;
            float tipLeadingZ = crankLeadingZ - outboardSweepBack;
            float tipTrailingZ = tipLeadingZ - tipChordLength;

            // Wound leading-edge-root -> crank -> tip -> trailing-edge-tip -> crank -> root,
            // i.e. all the way around the hexagon once — the same winding convention
            // CreateTaperedWing's quad uses, just with two extra crank vertices.
            Vector2[] rightHalfPlanform =
            {
                new Vector2(0f, rootLeadingZ),
                new Vector2(crankX, crankLeadingZ),
                new Vector2(halfSpan, tipLeadingZ),
                new Vector2(halfSpan, tipTrailingZ),
                new Vector2(crankX, crankTrailingZ),
                new Vector2(0f, rootTrailingZ),
            };

            var mesh = new Mesh { name = "ProceduralKiteWing" };
            var vertices = new System.Collections.Generic.List<Vector3>();
            var triangles = new System.Collections.Generic.List<int>();

            AddWingHalf(rightHalfPlanform, halfThickness, mirrorX: false, vertices, triangles);
            AddWingHalf(rightHalfPlanform, halfThickness, mirrorX: true, vertices, triangles);

            mesh.SetVertices(vertices);
            mesh.SetTriangles(triangles, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        private static void AddWingHalf(Vector2[] planform, float halfThickness, bool mirrorX,
            System.Collections.Generic.List<Vector3> vertices, System.Collections.Generic.List<int> triangles)
        {
            float sign = mirrorX ? -1f : 1f;
            int baseIndex = vertices.Count;

            // Top face ring, then bottom face ring (same XZ footprint, offset in Y).
            foreach (var point in planform)
                vertices.Add(new Vector3(point.x * sign, halfThickness, point.y));
            foreach (var point in planform)
                vertices.Add(new Vector3(point.x * sign, -halfThickness, point.y));

            int pointCount = planform.Length;

            // Top/bottom faces: fan-triangulate from vertex 0, winding flipped when
            // mirrored so both halves face upward consistently; bottom face winds the
            // opposite way from top so it faces downward.
            for (int i = 1; i < pointCount - 1; i++)
            {
                AddTriangle(triangles, baseIndex, 0, i, i + 1, mirrorX);
                AddTriangle(triangles, baseIndex, pointCount + 0, pointCount + (i + 1), pointCount + i, mirrorX);
            }

            // Edge (side) faces connecting top ring to bottom ring around the perimeter,
            // so the wing reads as a solid prism rather than two floating flat quads.
            for (int i = 0; i < pointCount; i++)
            {
                int next = (i + 1) % pointCount;
                AddTriangle(triangles, baseIndex, i, next, pointCount + next, mirrorX);
                AddTriangle(triangles, baseIndex, i, pointCount + next, pointCount + i, mirrorX);
            }
        }

        private static void AddTriangle(System.Collections.Generic.List<int> triangles, int baseIndex,
            int a, int b, int c, bool flipWinding)
        {
            if (flipWinding)
            {
                triangles.Add(baseIndex + a);
                triangles.Add(baseIndex + c);
                triangles.Add(baseIndex + b);
            }
            else
            {
                triangles.Add(baseIndex + a);
                triangles.Add(baseIndex + b);
                triangles.Add(baseIndex + c);
            }
        }
    }
}
